namespace AoTEngine.Models;

/// <summary>
/// Represents a structured summary record for a single task.
/// Used for documentation output and fine-tuning dataset generation.
/// </summary>
public class TaskSummaryRecord
{
    /// <summary>
    /// Unique identifier for the task.
    /// </summary>
    public string TaskId { get; set; } = string.Empty;

    /// <summary>
    /// Description of the task from the decomposition phase.
    /// </summary>
    public string TaskDescription { get; set; } = string.Empty;

    /// <summary>
    /// List of task IDs that this task depends on.
    /// </summary>
    public List<string> Dependencies { get; set; } = new();

    /// <summary>
    /// Expected type names generated by this task.
    /// </summary>
    public List<string> ExpectedTypes { get; set; } = new();

    /// <summary>
    /// Namespace where the generated code resides.
    /// </summary>
    public string Namespace { get; set; } = string.Empty;

    /// <summary>
    /// Short description of the task's purpose.
    /// </summary>
    public string Purpose { get; set; } = string.Empty;

    /// <summary>
    /// Key behaviors implemented by the task's code.
    /// </summary>
    public List<string> KeyBehaviors { get; set; } = new();

    /// <summary>
    /// Edge cases handled by the task's code.
    /// </summary>
    public List<string> EdgeCases { get; set; } = new();

    /// <summary>
    /// Notes about validation, including attempt count and any errors encountered.
    /// </summary>
    public string ValidationNotes { get; set; } = string.Empty;

    /// <summary>
    /// Hash of the generated code for tracking purposes.
    /// </summary>
    public string GeneratedCodeHash { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp when the summary was created.
    /// </summary>
    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// The generated code snippet for this task.
    /// </summary>
    public string GeneratedCode { get; set; } = string.Empty;

    /// <summary>
    /// The model used to generate the summary.
    /// </summary>
    public string SummaryModel { get; set; } = string.Empty;
}
